version: '2'
services:
  shiftscheduling:
    image: shiftscheduling:0.0.1
    restart: always
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DB_SCHEMA_NAME=shiftdb
      - INITIALISE_DATABASE_TABLES=false
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  mysqldb:
    image: mysql:5.7.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin

  elasticsearch:
    image: elasticsearch:2.3.2
    restart: always
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - SHIFT_INDEX_NAME=shift_repo
      - SHIFT_INDEX_DOCTYPE=item
      - EMPLOYEE_INDEX_NAME=shift_employees
      - EMPLOYEE_INDEX_DOCTYPE=employee
      - LOG_INDEX_NAME=shift_logs
      - LOG_INDEX_DOCTYPE=log

  rabbitmq:
    image: rabbitmq:3.6.1-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin